### ISSUE TITLE
Remove analytics code from source code

### ISSUE THREAD

**Issue by davefp** [paracycle/slackthemes#17]
You've got your Google Analytics token in config.rb: https://github.com/paracycle/slackthemes/blob/master/config.rb#L80

I recommend moving it to a config file that lives outside public source control so that you don't start getting spurious records from people who clone and run this project elsewhere.

**Comment by paracycle** [comment]
Hey, thank you so much for pointing that out. I added GA at the last minute just before I released this, so I missed that. I added `dotenv` to make it easier to work with a local `.env` file: https://github.com/paracycle/slackthemes/commit/bb41d048598e0c3ee986ae48e54e4380e038ff99
