### ISSUE TITLE
How can I compile/build the project?

### ISSUE THREAD

**Issue by jschouwstra** [paracycle/slackthemes#195]
How can I compile/build the project to usable html files?

**Comment by wopian** [comment]
See https://github.com/paracycle/slackthemes/pull/114#pullrequestreview-17091810

Full requirements are listed on my fork: [wopian/material-slackthemes#development](https://github.com/wopian/material-slackthemes#development)

**Comment by paracycle** [comment]
Thanks for stepping in @wopian! 👍
