### ISSUE TITLE
Remove ugly themes

### ISSUE THREAD

**Issue by atesgoral** [paracycle/slackthemes#20]
There might be [some themes](http://slackthemes.net/#/summer_craze) that are not as pretty as other themes. Would it make sense to cull some themes? It would even be nicer if there was a way to track popularity of themes and cull unpopular ones...

**Comment by IgorAntun** [comment]
Agreed. This hurt my eyes lol.

**Comment by paracycle** [comment]
I don't really mind that there are some ugly themes out there. My initial aim for this was for it to be a compendium of themes that people might want to use. I don't find it fair for me to pass judgement on what people might find pleasing or not.

Keeping track of popular themes is a good idea and can most easily be achieved by sending synthetic page view events to GA for every theme selection. I'll open another issue for that and see what I can do.
