### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by falnyr** [paracycle/slackthemes#275]
Since [Slack announced dark theme support](https://twitter.com/SlackHQ/status/1172165133956603904), could this be added as an option?

**Comment by paracycle** [comment]
Now that I've moved the site to the new Slack UI, I will be thinking about how to add this in an elegant way. The basic functionality already exists in the CSS and can be activated by one class change, but I need a good way to surface the toggle without sacrificing the UI.
