### ISSUE TITLE
New Feature Request: Toggle On Multi-Team View Or Single View

### ISSUE THREAD

**Issue by mattisdada** [paracycle/slackthemes#73]
I would like to have the ability to toggle showing what a "single team" view and "multi-team" view looks like. Some of the themes look really good on single team, but look awful on multi-team (Midnight Pink is a prime example)

As on the multi team, side bar changes color, and the bottom "profile" disappears (will be the same color as the profile part down the bottom)

Example:
![image](https://cloud.githubusercontent.com/assets/314500/13970100/dc4b2802-f0da-11e5-9fa3-cff4abcea10b.png)

**Comment by FrontEndCoffee** [comment]
I'm all for adding the team switching sidebar! 

Do users have to be able to switch it off though? I don't see the added value of a single-team view considering the toggle will add complexity to the UI.

I would suggest just adding the team switch bar, as it is a part of Slack.

**Comment by paracycle** [comment]
Team switching bar is added as part of #300.
