### ISSUE TITLE
Sort themes in case-insensitive manner

### ISSUE THREAD

**Issue by paracycle** [paracycle/slackthemes#80]

**Comment by Hipska** [comment]
I would love to see the themes.yml sorted by name.

I think it will improve the easiness of merges from pull request if not every new theme is added to the end.

**Comment by paracycle** [comment]
@hipska I did think about doing that but I don't want to deal with the extra chore of keeping themes in alphabetical order when the computer is perfectly capable of doing that at build time. It would also make contribution a little bit harder since people would need to know to put the new themes in the right place.

The way it is now, it works well with the simple merge conflict editor on the Github interface so it's really easy to merge contributions.

**Comment by paracycle** [comment]
This is fixed by https://github.com/paracycle/slackthemes/commit/4dcba4c83232b5acebfadf0d016d3b0f85d04544

**Comment by Hipska** [comment]
Okay, fine for me. But Git history becomes a mess 😛

**Comment by paracycle** [comment]
Right, that was indeed a problem so I've started to squash merge PRs. It helps keep the history tidy. 😉
